//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratixRuanDataLayer.StratixAuthenticationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stratix.invera.com/services", ConfigurationName="StratixAuthenticationService.AuthenticationService")]
    public interface AuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Login", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/Login", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.LoginResponse Login(StratixRuanDataLayer.StratixAuthenticationService.LoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LoginResponse> LoginAsync(StratixRuanDataLayer.StratixAuthenticationService.LoginRequest request);
        
        // CODEGEN: Generating message contract since message LogoutResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Logout", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/Logout", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse Logout(StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse> LogoutAsync(StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest request);
        
        // CODEGEN: Generating message contract since message ConsumeLicenseResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ConsumeLicense", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/ConsumeLicense", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse ConsumeLicense(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ConsumeLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse> ConsumeLicenseAsync(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/LoginAndChangePassword", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/LoginAndChangePassword", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordResponse LoginAndChangePassword(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/LoginAndChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordResponse> LoginAndChangePasswordAsync(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/ChangePassword", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponse ChangePassword(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponse> ChangePasswordAsync(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ChangePasswordForUser", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/ChangePasswordForUser", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserResponse ChangePasswordForUser(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/ChangePasswordForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserResponse> ChangePasswordForUserAsync(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/GetPasswordPolicy", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/GetPasswordPolicy", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponse GetPasswordPolicy(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/GetPasswordPolicy", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponse> GetPasswordPolicyAsync(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest request);
        
        // CODEGEN: Generating message contract since message GatewayLoginResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/GatewayLogin", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/GatewayLogin", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse GatewayLogin(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/GatewayLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse> GatewayLoginAsync(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest request);
        
        // CODEGEN: Generating message contract since message ValidateResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Validate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/Validate", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse Validate(StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse> ValidateAsync(StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest request);
        
        // CODEGEN: Generating message contract since message IsConnectedResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/IsConnected", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/IsConnected", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse IsConnected(StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/IsConnected", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse> IsConnectedAsync(StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class LoginRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string connectedSessionTypeField;
        
        private string connectedServerField;
        
        private int connectedPortField;
        
        private bool connectedPortFieldSpecified;
        
        private string environmentNameField;
        
        private string primaryServerField;
        
        private bool forceDisconnectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string connectedSessionType {
            get {
                return this.connectedSessionTypeField;
            }
            set {
                this.connectedSessionTypeField = value;
                this.RaisePropertyChanged("connectedSessionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string connectedServer {
            get {
                return this.connectedServerField;
            }
            set {
                this.connectedServerField = value;
                this.RaisePropertyChanged("connectedServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int connectedPort {
            get {
                return this.connectedPortField;
            }
            set {
                this.connectedPortField = value;
                this.RaisePropertyChanged("connectedPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedPortSpecified {
            get {
                return this.connectedPortFieldSpecified;
            }
            set {
                this.connectedPortFieldSpecified = value;
                this.RaisePropertyChanged("connectedPortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string environmentName {
            get {
                return this.environmentNameField;
            }
            set {
                this.environmentNameField = value;
                this.RaisePropertyChanged("environmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primaryServer {
            get {
                return this.primaryServerField;
            }
            set {
                this.primaryServerField = value;
                this.RaisePropertyChanged("primaryServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool forceDisconnect {
            get {
                return this.forceDisconnectField;
            }
            set {
                this.forceDisconnectField = value;
                this.RaisePropertyChanged("forceDisconnect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class GatewayLoginResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationToken authenticationTokenField;
        
        private string connectedServerField;
        
        private int connectedPortField;
        
        private bool connectedPortFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AuthenticationToken authenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("authenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string connectedServer {
            get {
                return this.connectedServerField;
            }
            set {
                this.connectedServerField = value;
                this.RaisePropertyChanged("connectedServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int connectedPort {
            get {
                return this.connectedPortField;
            }
            set {
                this.connectedPortField = value;
                this.RaisePropertyChanged("connectedPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedPortSpecified {
            get {
                return this.connectedPortFieldSpecified;
            }
            set {
                this.connectedPortFieldSpecified = value;
                this.RaisePropertyChanged("connectedPortSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class AuthenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class GatewayLoginRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string companyIdField;
        
        private string connectedAccessTypeField;
        
        private string environmentNameField;
        
        private string environmentClassField;
        
        private bool forceDisconnectField;
        
        private bool forceDisconnectFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("companyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string connectedAccessType {
            get {
                return this.connectedAccessTypeField;
            }
            set {
                this.connectedAccessTypeField = value;
                this.RaisePropertyChanged("connectedAccessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string environmentName {
            get {
                return this.environmentNameField;
            }
            set {
                this.environmentNameField = value;
                this.RaisePropertyChanged("environmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string environmentClass {
            get {
                return this.environmentClassField;
            }
            set {
                this.environmentClassField = value;
                this.RaisePropertyChanged("environmentClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool forceDisconnect {
            get {
                return this.forceDisconnectField;
            }
            set {
                this.forceDisconnectField = value;
                this.RaisePropertyChanged("forceDisconnect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forceDisconnectSpecified {
            get {
                return this.forceDisconnectFieldSpecified;
            }
            set {
                this.forceDisconnectFieldSpecified = value;
                this.RaisePropertyChanged("forceDisconnectSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class GetPasswordPolicyResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool unrepeatablePasswordCycleField;
        
        private int minimumPasswordLengthField;
        
        private bool alphaAndNumericCharactersRequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool unrepeatablePasswordCycle {
            get {
                return this.unrepeatablePasswordCycleField;
            }
            set {
                this.unrepeatablePasswordCycleField = value;
                this.RaisePropertyChanged("unrepeatablePasswordCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int minimumPasswordLength {
            get {
                return this.minimumPasswordLengthField;
            }
            set {
                this.minimumPasswordLengthField = value;
                this.RaisePropertyChanged("minimumPasswordLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool alphaAndNumericCharactersRequired {
            get {
                return this.alphaAndNumericCharactersRequiredField;
            }
            set {
                this.alphaAndNumericCharactersRequiredField = value;
                this.RaisePropertyChanged("alphaAndNumericCharactersRequired");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class GetPasswordPolicyRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class ChangePasswordForUserRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationToken authenticationTokenField;
        
        private string usernameField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AuthenticationToken authenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("authenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string newPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("newPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class ChangePasswordResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationToken authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AuthenticationToken authenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("authenticationToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class ChangePasswordRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationToken authenticationTokenField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AuthenticationToken authenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("authenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string newPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("newPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class LoginAndChangePasswordRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string newPasswordField;
        
        private string connectedSessionTypeField;
        
        private string connectedServerField;
        
        private int connectedPortField;
        
        private bool connectedPortFieldSpecified;
        
        private string environmentNameField;
        
        private string primaryServerField;
        
        private bool forceDisconnectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string newPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("newPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string connectedSessionType {
            get {
                return this.connectedSessionTypeField;
            }
            set {
                this.connectedSessionTypeField = value;
                this.RaisePropertyChanged("connectedSessionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string connectedServer {
            get {
                return this.connectedServerField;
            }
            set {
                this.connectedServerField = value;
                this.RaisePropertyChanged("connectedServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int connectedPort {
            get {
                return this.connectedPortField;
            }
            set {
                this.connectedPortField = value;
                this.RaisePropertyChanged("connectedPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedPortSpecified {
            get {
                return this.connectedPortFieldSpecified;
            }
            set {
                this.connectedPortFieldSpecified = value;
                this.RaisePropertyChanged("connectedPortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string environmentName {
            get {
                return this.environmentNameField;
            }
            set {
                this.environmentNameField = value;
                this.RaisePropertyChanged("environmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string primaryServer {
            get {
                return this.primaryServerField;
            }
            set {
                this.primaryServerField = value;
                this.RaisePropertyChanged("primaryServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool forceDisconnect {
            get {
                return this.forceDisconnectField;
            }
            set {
                this.forceDisconnectField = value;
                this.RaisePropertyChanged("forceDisconnect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class ConsumeLicenseResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string connectedServerField;
        
        private int connectedPortField;
        
        private bool connectedPortFieldSpecified;
        
        private string clntIdInfoField;
        
        private AuthenticationToken authTokenField;
        
        private string encryptedTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string connectedServer {
            get {
                return this.connectedServerField;
            }
            set {
                this.connectedServerField = value;
                this.RaisePropertyChanged("connectedServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int connectedPort {
            get {
                return this.connectedPortField;
            }
            set {
                this.connectedPortField = value;
                this.RaisePropertyChanged("connectedPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedPortSpecified {
            get {
                return this.connectedPortFieldSpecified;
            }
            set {
                this.connectedPortFieldSpecified = value;
                this.RaisePropertyChanged("connectedPortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clntIdInfo {
            get {
                return this.clntIdInfoField;
            }
            set {
                this.clntIdInfoField = value;
                this.RaisePropertyChanged("clntIdInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public AuthenticationToken authToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("authToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string encryptedTimestamp {
            get {
                return this.encryptedTimestampField;
            }
            set {
                this.encryptedTimestampField = value;
                this.RaisePropertyChanged("encryptedTimestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class ConsumeLicenseRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clntIdInfoField;
        
        private string envNmField;
        
        private string primSrvrField;
        
        private string envClField;
        
        private string licPrdIdField;
        
        private int delOldSsnField;
        
        private bool delOldSsnFieldSpecified;
        
        private string userField;
        
        private string languageField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clntIdInfo {
            get {
                return this.clntIdInfoField;
            }
            set {
                this.clntIdInfoField = value;
                this.RaisePropertyChanged("clntIdInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string envNm {
            get {
                return this.envNmField;
            }
            set {
                this.envNmField = value;
                this.RaisePropertyChanged("envNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string primSrvr {
            get {
                return this.primSrvrField;
            }
            set {
                this.primSrvrField = value;
                this.RaisePropertyChanged("primSrvr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string envCl {
            get {
                return this.envClField;
            }
            set {
                this.envClField = value;
                this.RaisePropertyChanged("envCl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string licPrdId {
            get {
                return this.licPrdIdField;
            }
            set {
                this.licPrdIdField = value;
                this.RaisePropertyChanged("licPrdId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int delOldSsn {
            get {
                return this.delOldSsnField;
            }
            set {
                this.delOldSsnField = value;
                this.RaisePropertyChanged("delOldSsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool delOldSsnSpecified {
            get {
                return this.delOldSsnFieldSpecified;
            }
            set {
                this.delOldSsnFieldSpecified = value;
                this.RaisePropertyChanged("delOldSsnSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class ServiceMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnStatusField;
        
        private string[] messageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
                this.RaisePropertyChanged("returnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("messageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class LoginResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationToken authenticationTokenField;
        
        private string countryField;
        
        private string languageField;
        
        private string customerIdField;
        
        private string isvUserTypeField;
        
        private bool unrepeatablePasswordCycleField;
        
        private int minimumPasswordLengthField;
        
        private bool alphaAndNumericCharactersRequiredField;
        
        private bool passwordChangeRequiredField;
        
        private string clntIdInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AuthenticationToken authenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("authenticationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isvUserType {
            get {
                return this.isvUserTypeField;
            }
            set {
                this.isvUserTypeField = value;
                this.RaisePropertyChanged("isvUserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool unrepeatablePasswordCycle {
            get {
                return this.unrepeatablePasswordCycleField;
            }
            set {
                this.unrepeatablePasswordCycleField = value;
                this.RaisePropertyChanged("unrepeatablePasswordCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int minimumPasswordLength {
            get {
                return this.minimumPasswordLengthField;
            }
            set {
                this.minimumPasswordLengthField = value;
                this.RaisePropertyChanged("minimumPasswordLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool alphaAndNumericCharactersRequired {
            get {
                return this.alphaAndNumericCharactersRequiredField;
            }
            set {
                this.alphaAndNumericCharactersRequiredField = value;
                this.RaisePropertyChanged("alphaAndNumericCharactersRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool passwordChangeRequired {
            get {
                return this.passwordChangeRequiredField;
            }
            set {
                this.passwordChangeRequiredField = value;
                this.RaisePropertyChanged("passwordChangeRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string clntIdInfo {
            get {
                return this.clntIdInfoField;
            }
            set {
                this.clntIdInfoField = value;
                this.RaisePropertyChanged("clntIdInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.LoginRequestType input;
        
        public LoginRequest() {
        }
        
        public LoginRequest(StratixRuanDataLayer.StratixAuthenticationService.LoginRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input;
        
        public LoginResponse() {
        }
        
        public LoginResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.AuthenticationToken authenticationToken;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(StratixRuanDataLayer.StratixAuthenticationService.AuthenticationToken authenticationToken) {
            this.authenticationToken = authenticationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumeLicense", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ConsumeLicenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequestType input;
        
        public ConsumeLicenseRequest() {
        }
        
        public ConsumeLicenseRequest(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumeLicenseResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ConsumeLicenseResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponseType output;
        
        public ConsumeLicenseResponse() {
        }
        
        public ConsumeLicenseResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponseType output) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndChangePassword", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LoginAndChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequestType input;
        
        public LoginAndChangePasswordRequest() {
        }
        
        public LoginAndChangePasswordRequest(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndChangePasswordResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LoginAndChangePasswordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input;
        
        public LoginAndChangePasswordResponse() {
        }
        
        public LoginAndChangePasswordResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequestType input;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordForUser", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ChangePasswordForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequestType input;
        
        public ChangePasswordForUserRequest() {
        }
        
        public ChangePasswordForUserRequest(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordForUserResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ChangePasswordForUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input;
        
        public ChangePasswordForUserResponse() {
        }
        
        public ChangePasswordForUserResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPasswordPolicy", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class GetPasswordPolicyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequestType input;
        
        public GetPasswordPolicyRequest() {
        }
        
        public GetPasswordPolicyRequest(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPasswordPolicyResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class GetPasswordPolicyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponseType input;
        
        public GetPasswordPolicyResponse() {
        }
        
        public GetPasswordPolicyResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponseType input) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GatewayLogin", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class GatewayLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequestType input;
        
        public GatewayLoginRequest() {
        }
        
        public GatewayLoginRequest(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequestType input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GatewayLoginResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class GatewayLoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponseType response;
        
        public GatewayLoginResponse() {
        }
        
        public GatewayLoginResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader, StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponseType response) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Validate", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string execLgnId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pwd;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(string execLgnId, string pwd) {
            this.execLgnId = execLgnId;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsConnected", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class IsConnectedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string execLgnId;
        
        public IsConnectedRequest() {
        }
        
        public IsConnectedRequest(string execLgnId) {
            this.execLgnId = execLgnId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsConnectedResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class IsConnectedResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader;
        
        public IsConnectedResponse() {
        }
        
        public IsConnectedResponse(StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ServiceMessagesHeader) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServiceChannel : StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService>, StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.LoginResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.Login(StratixRuanDataLayer.StratixAuthenticationService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages Login(StratixRuanDataLayer.StratixAuthenticationService.LoginRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input1) {
            StratixRuanDataLayer.StratixAuthenticationService.LoginRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.LoginRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.LoginResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).Login(inValue);
            input1 = retVal.input;
            return retVal.ServiceMessagesHeader;
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LoginResponse> LoginAsync(StratixRuanDataLayer.StratixAuthenticationService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.Logout(StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages Logout(StratixRuanDataLayer.StratixAuthenticationService.AuthenticationToken authenticationToken) {
            StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest();
            inValue.authenticationToken = authenticationToken;
            StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).Logout(inValue);
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse> StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.LogoutAsync(StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LogoutResponse> LogoutAsync(StratixRuanDataLayer.StratixAuthenticationService.AuthenticationToken authenticationToken) {
            StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.LogoutRequest();
            inValue.authenticationToken = authenticationToken;
            return ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.ConsumeLicense(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest request) {
            return base.Channel.ConsumeLicense(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ConsumeLicense(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponseType output) {
            StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).ConsumeLicense(inValue);
            output = retVal.output;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse> StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.ConsumeLicenseAsync(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest request) {
            return base.Channel.ConsumeLicenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseResponse> ConsumeLicenseAsync(StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequestType input) {
            StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ConsumeLicenseRequest();
            inValue.input = input;
            return ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).ConsumeLicenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.LoginAndChangePassword(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest request) {
            return base.Channel.LoginAndChangePassword(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages LoginAndChangePassword(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.LoginResponseType input1) {
            StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).LoginAndChangePassword(inValue);
            input1 = retVal.input;
            return retVal.ServiceMessagesHeader;
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordResponse> LoginAndChangePasswordAsync(StratixRuanDataLayer.StratixAuthenticationService.LoginAndChangePasswordRequest request) {
            return base.Channel.LoginAndChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.ChangePassword(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ChangePassword(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input1) {
            StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).ChangePassword(inValue);
            input1 = retVal.input;
            return retVal.ServiceMessagesHeader;
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponse> ChangePasswordAsync(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.ChangePasswordForUser(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest request) {
            return base.Channel.ChangePasswordForUser(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages ChangePasswordForUser(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordResponseType input1) {
            StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).ChangePasswordForUser(inValue);
            input1 = retVal.input;
            return retVal.ServiceMessagesHeader;
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserResponse> ChangePasswordForUserAsync(StratixRuanDataLayer.StratixAuthenticationService.ChangePasswordForUserRequest request) {
            return base.Channel.ChangePasswordForUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.GetPasswordPolicy(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest request) {
            return base.Channel.GetPasswordPolicy(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages GetPasswordPolicy(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponseType input1) {
            StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).GetPasswordPolicy(inValue);
            input1 = retVal.input;
            return retVal.ServiceMessagesHeader;
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyResponse> GetPasswordPolicyAsync(StratixRuanDataLayer.StratixAuthenticationService.GetPasswordPolicyRequest request) {
            return base.Channel.GetPasswordPolicyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.GatewayLogin(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest request) {
            return base.Channel.GatewayLogin(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages GatewayLogin(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequestType input, out StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponseType response) {
            StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest();
            inValue.input = input;
            StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).GatewayLogin(inValue);
            response = retVal.response;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse> StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.GatewayLoginAsync(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest request) {
            return base.Channel.GatewayLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginResponse> GatewayLoginAsync(StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequestType input) {
            StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.GatewayLoginRequest();
            inValue.input = input;
            return ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).GatewayLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.Validate(StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages Validate(string execLgnId, string pwd) {
            StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest();
            inValue.execLgnId = execLgnId;
            inValue.pwd = pwd;
            StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).Validate(inValue);
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse> StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.ValidateAsync(StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.ValidateResponse> ValidateAsync(string execLgnId, string pwd) {
            StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.ValidateRequest();
            inValue.execLgnId = execLgnId;
            inValue.pwd = pwd;
            return ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).ValidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.IsConnected(StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest request) {
            return base.Channel.IsConnected(request);
        }
        
        public StratixRuanDataLayer.StratixAuthenticationService.ServiceMessages IsConnected(string execLgnId) {
            StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest();
            inValue.execLgnId = execLgnId;
            StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse retVal = ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).IsConnected(inValue);
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse> StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService.IsConnectedAsync(StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest request) {
            return base.Channel.IsConnectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixAuthenticationService.IsConnectedResponse> IsConnectedAsync(string execLgnId) {
            StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest inValue = new StratixRuanDataLayer.StratixAuthenticationService.IsConnectedRequest();
            inValue.execLgnId = execLgnId;
            return ((StratixRuanDataLayer.StratixAuthenticationService.AuthenticationService)(this)).IsConnectedAsync(inValue);
        }
    }
}
