//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratixRuanDataLayer.StratixTransportFreightService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stratix.invera.com/services", ConfigurationName="StratixTransportFreightService.TransportFreightService")]
    public interface TransportFreightService {
        
        // CODEGEN: Generating message contract since message UpdateTRFreightRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateTRFreight", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/UpdateTRFreight", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse UpdateTRFreight(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateTRFreight", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse> UpdateTRFreightAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest request);
        
        // CODEGEN: Generating message contract since message UpdateTRFreightCostRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateTRFreightCost", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/UpdateTRFreightCost", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse UpdateTRFreightCost(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateTRFreightCost", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse> UpdateTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest request);
        
        // CODEGEN: Generating message contract since message DeleteTRFreightCostRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/DeleteTRFreightCost", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/DeleteTRFreightCost", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse DeleteTRFreightCost(StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/DeleteTRFreightCost", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse> DeleteTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest request);
        
        // CODEGEN: Generating message contract since message UpdateMvtFreightCostRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateMvtFreightCost", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/UpdateMvtFreightCost", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse UpdateMvtFreightCost(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateMvtFreightCost", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse> UpdateMvtFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest request);
        
        // CODEGEN: Generating message contract since message UpdateMvtFreightChargeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateMvtFreightCharge", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/services/UpdateMvtFreightCharge", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse UpdateMvtFreightCharge(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/services/UpdateMvtFreightCharge", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse> UpdateMvtFreightChargeAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class AuthenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class UpdateMvtFreightChargeInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trNumberField;
        
        private int trMvtNumberField;
        
        private decimal mvtFreightChargeField;
        
        private bool mvtFreightChargeFieldSpecified;
        
        private string mvtFreightChargeUMField;
        
        private decimal mvtFlSurChrgChargeField;
        
        private bool mvtFlSurChrgChargeFieldSpecified;
        
        private string mvtFlSurChrgChargeUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int trNumber {
            get {
                return this.trNumberField;
            }
            set {
                this.trNumberField = value;
                this.RaisePropertyChanged("trNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int trMvtNumber {
            get {
                return this.trMvtNumberField;
            }
            set {
                this.trMvtNumberField = value;
                this.RaisePropertyChanged("trMvtNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal mvtFreightCharge {
            get {
                return this.mvtFreightChargeField;
            }
            set {
                this.mvtFreightChargeField = value;
                this.RaisePropertyChanged("mvtFreightCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mvtFreightChargeSpecified {
            get {
                return this.mvtFreightChargeFieldSpecified;
            }
            set {
                this.mvtFreightChargeFieldSpecified = value;
                this.RaisePropertyChanged("mvtFreightChargeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mvtFreightChargeUM {
            get {
                return this.mvtFreightChargeUMField;
            }
            set {
                this.mvtFreightChargeUMField = value;
                this.RaisePropertyChanged("mvtFreightChargeUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal mvtFlSurChrgCharge {
            get {
                return this.mvtFlSurChrgChargeField;
            }
            set {
                this.mvtFlSurChrgChargeField = value;
                this.RaisePropertyChanged("mvtFlSurChrgCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mvtFlSurChrgChargeSpecified {
            get {
                return this.mvtFlSurChrgChargeFieldSpecified;
            }
            set {
                this.mvtFlSurChrgChargeFieldSpecified = value;
                this.RaisePropertyChanged("mvtFlSurChrgChargeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mvtFlSurChrgChargeUM {
            get {
                return this.mvtFlSurChrgChargeUMField;
            }
            set {
                this.mvtFlSurChrgChargeUMField = value;
                this.RaisePropertyChanged("mvtFlSurChrgChargeUM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class UpdateMvtFreightCostInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trNumberField;
        
        private int trMvtNumberField;
        
        private decimal mvtFreightCostField;
        
        private bool mvtFreightCostFieldSpecified;
        
        private string mvtFreightCostUMField;
        
        private decimal mvtFlSurChrgCostField;
        
        private bool mvtFlSurChrgCostFieldSpecified;
        
        private string mvtFlSurChrgCostUMField;
        
        private string mvtCarrierRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int trNumber {
            get {
                return this.trNumberField;
            }
            set {
                this.trNumberField = value;
                this.RaisePropertyChanged("trNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int trMvtNumber {
            get {
                return this.trMvtNumberField;
            }
            set {
                this.trMvtNumberField = value;
                this.RaisePropertyChanged("trMvtNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal mvtFreightCost {
            get {
                return this.mvtFreightCostField;
            }
            set {
                this.mvtFreightCostField = value;
                this.RaisePropertyChanged("mvtFreightCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mvtFreightCostSpecified {
            get {
                return this.mvtFreightCostFieldSpecified;
            }
            set {
                this.mvtFreightCostFieldSpecified = value;
                this.RaisePropertyChanged("mvtFreightCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mvtFreightCostUM {
            get {
                return this.mvtFreightCostUMField;
            }
            set {
                this.mvtFreightCostUMField = value;
                this.RaisePropertyChanged("mvtFreightCostUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal mvtFlSurChrgCost {
            get {
                return this.mvtFlSurChrgCostField;
            }
            set {
                this.mvtFlSurChrgCostField = value;
                this.RaisePropertyChanged("mvtFlSurChrgCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mvtFlSurChrgCostSpecified {
            get {
                return this.mvtFlSurChrgCostFieldSpecified;
            }
            set {
                this.mvtFlSurChrgCostFieldSpecified = value;
                this.RaisePropertyChanged("mvtFlSurChrgCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mvtFlSurChrgCostUM {
            get {
                return this.mvtFlSurChrgCostUMField;
            }
            set {
                this.mvtFlSurChrgCostUMField = value;
                this.RaisePropertyChanged("mvtFlSurChrgCostUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mvtCarrierRef {
            get {
                return this.mvtCarrierRefField;
            }
            set {
                this.mvtCarrierRefField = value;
                this.RaisePropertyChanged("mvtCarrierRef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class UpdateTRFreightCostInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trNumberField;
        
        private decimal trFreightCostField;
        
        private bool trFreightCostFieldSpecified;
        
        private string trFreightCostUMField;
        
        private decimal trFlSurChrgCostField;
        
        private bool trFlSurChrgCostFieldSpecified;
        
        private string trFlSurChrgCostUMField;
        
        private decimal trStopChrgField;
        
        private bool trStopChrgFieldSpecified;
        
        private string trCarrierRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int trNumber {
            get {
                return this.trNumberField;
            }
            set {
                this.trNumberField = value;
                this.RaisePropertyChanged("trNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal trFreightCost {
            get {
                return this.trFreightCostField;
            }
            set {
                this.trFreightCostField = value;
                this.RaisePropertyChanged("trFreightCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trFreightCostSpecified {
            get {
                return this.trFreightCostFieldSpecified;
            }
            set {
                this.trFreightCostFieldSpecified = value;
                this.RaisePropertyChanged("trFreightCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string trFreightCostUM {
            get {
                return this.trFreightCostUMField;
            }
            set {
                this.trFreightCostUMField = value;
                this.RaisePropertyChanged("trFreightCostUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal trFlSurChrgCost {
            get {
                return this.trFlSurChrgCostField;
            }
            set {
                this.trFlSurChrgCostField = value;
                this.RaisePropertyChanged("trFlSurChrgCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trFlSurChrgCostSpecified {
            get {
                return this.trFlSurChrgCostFieldSpecified;
            }
            set {
                this.trFlSurChrgCostFieldSpecified = value;
                this.RaisePropertyChanged("trFlSurChrgCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string trFlSurChrgCostUM {
            get {
                return this.trFlSurChrgCostUMField;
            }
            set {
                this.trFlSurChrgCostUMField = value;
                this.RaisePropertyChanged("trFlSurChrgCostUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal trStopChrg {
            get {
                return this.trStopChrgField;
            }
            set {
                this.trStopChrgField = value;
                this.RaisePropertyChanged("trStopChrg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trStopChrgSpecified {
            get {
                return this.trStopChrgFieldSpecified;
            }
            set {
                this.trStopChrgFieldSpecified = value;
                this.RaisePropertyChanged("trStopChrgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string trCarrierRef {
            get {
                return this.trCarrierRefField;
            }
            set {
                this.trCarrierRefField = value;
                this.RaisePropertyChanged("trCarrierRef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class DataElementMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataElementField;
        
        private string[] messageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataElement {
            get {
                return this.dataElementField;
            }
            set {
                this.dataElementField = value;
                this.RaisePropertyChanged("dataElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("messageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class ServiceMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnStatusField;
        
        private string[] messageListField;
        
        private DataElementMessageList[] dataElementMessageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
                this.RaisePropertyChanged("returnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("messageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataElementMessageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public DataElementMessageList[] dataElementMessageList {
            get {
                return this.dataElementMessageListField;
            }
            set {
                this.dataElementMessageListField = value;
                this.RaisePropertyChanged("dataElementMessageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/services")]
    public partial class UpdateTRFreightInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int trNumberField;
        
        private string trDlvyMthdField;
        
        private string trFreightVenIDField;
        
        private string trCarrierNmField;
        
        private string trCurrencyField;
        
        private string trExchangeRtTypeField;
        
        private decimal trExchangeRtField;
        
        private bool trExchangeRtFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int trNumber {
            get {
                return this.trNumberField;
            }
            set {
                this.trNumberField = value;
                this.RaisePropertyChanged("trNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string trDlvyMthd {
            get {
                return this.trDlvyMthdField;
            }
            set {
                this.trDlvyMthdField = value;
                this.RaisePropertyChanged("trDlvyMthd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string trFreightVenID {
            get {
                return this.trFreightVenIDField;
            }
            set {
                this.trFreightVenIDField = value;
                this.RaisePropertyChanged("trFreightVenID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string trCarrierNm {
            get {
                return this.trCarrierNmField;
            }
            set {
                this.trCarrierNmField = value;
                this.RaisePropertyChanged("trCarrierNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string trCurrency {
            get {
                return this.trCurrencyField;
            }
            set {
                this.trCurrencyField = value;
                this.RaisePropertyChanged("trCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string trExchangeRtType {
            get {
                return this.trExchangeRtTypeField;
            }
            set {
                this.trExchangeRtTypeField = value;
                this.RaisePropertyChanged("trExchangeRtType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal trExchangeRt {
            get {
                return this.trExchangeRtField;
            }
            set {
                this.trExchangeRtField = value;
                this.RaisePropertyChanged("trExchangeRt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trExchangeRtSpecified {
            get {
                return this.trExchangeRtFieldSpecified;
            }
            set {
                this.trExchangeRtFieldSpecified = value;
                this.RaisePropertyChanged("trExchangeRtSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTRFreight", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateTRFreightRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightInput updateTRFreightInput;
        
        public UpdateTRFreightRequest() {
        }
        
        public UpdateTRFreightRequest(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightInput updateTRFreightInput) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.updateTRFreightInput = updateTRFreightInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTRFreightResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateTRFreightResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader;
        
        public UpdateTRFreightResponse() {
        }
        
        public UpdateTRFreightResponse(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTRFreightCost", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateTRFreightCostRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostInput updateTRFreightCostInput;
        
        public UpdateTRFreightCostRequest() {
        }
        
        public UpdateTRFreightCostRequest(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostInput updateTRFreightCostInput) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.updateTRFreightCostInput = updateTRFreightCostInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTRFreightCostResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateTRFreightCostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader;
        
        public UpdateTRFreightCostResponse() {
        }
        
        public UpdateTRFreightCostResponse(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTRFreightCost", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class DeleteTRFreightCostRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trNumber;
        
        public DeleteTRFreightCostRequest() {
        }
        
        public DeleteTRFreightCostRequest(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, int trNumber) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.trNumber = trNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTRFreightCostResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class DeleteTRFreightCostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader;
        
        public DeleteTRFreightCostResponse() {
        }
        
        public DeleteTRFreightCostResponse(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMvtFreightCost", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateMvtFreightCostRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostInput updateMvtFreightCostInput;
        
        public UpdateMvtFreightCostRequest() {
        }
        
        public UpdateMvtFreightCostRequest(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostInput updateMvtFreightCostInput) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.updateMvtFreightCostInput = updateMvtFreightCostInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMvtFreightCostResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateMvtFreightCostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader;
        
        public UpdateMvtFreightCostResponse() {
        }
        
        public UpdateMvtFreightCostResponse(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMvtFreightCharge", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateMvtFreightChargeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeInput updateMvtFreightChargeInput;
        
        public UpdateMvtFreightChargeRequest() {
        }
        
        public UpdateMvtFreightChargeRequest(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeInput updateMvtFreightChargeInput) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.updateMvtFreightChargeInput = updateMvtFreightChargeInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMvtFreightChargeResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class UpdateMvtFreightChargeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader;
        
        public UpdateMvtFreightChargeResponse() {
        }
        
        public UpdateMvtFreightChargeResponse(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages ServiceMessagesHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportFreightServiceChannel : StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportFreightServiceClient : System.ServiceModel.ClientBase<StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService>, StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService {
        
        public TransportFreightServiceClient() {
        }
        
        public TransportFreightServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportFreightServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportFreightServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportFreightServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateTRFreight(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest request) {
            return base.Channel.UpdateTRFreight(request);
        }
        
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages UpdateTRFreight(ref StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightInput updateTRFreightInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateTRFreightInput = updateTRFreightInput;
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse retVal = ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateTRFreight(inValue);
            AuthenticationHeader = retVal.AuthenticationHeader;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse> StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateTRFreightAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest request) {
            return base.Channel.UpdateTRFreightAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightResponse> UpdateTRFreightAsync(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightInput updateTRFreightInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateTRFreightInput = updateTRFreightInput;
            return ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateTRFreightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateTRFreightCost(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest request) {
            return base.Channel.UpdateTRFreightCost(request);
        }
        
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages UpdateTRFreightCost(ref StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostInput updateTRFreightCostInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateTRFreightCostInput = updateTRFreightCostInput;
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse retVal = ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateTRFreightCost(inValue);
            AuthenticationHeader = retVal.AuthenticationHeader;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse> StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest request) {
            return base.Channel.UpdateTRFreightCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostResponse> UpdateTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostInput updateTRFreightCostInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateTRFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateTRFreightCostInput = updateTRFreightCostInput;
            return ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateTRFreightCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.DeleteTRFreightCost(StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest request) {
            return base.Channel.DeleteTRFreightCost(request);
        }
        
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages DeleteTRFreightCost(ref StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, int trNumber) {
            StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.trNumber = trNumber;
            StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse retVal = ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).DeleteTRFreightCost(inValue);
            AuthenticationHeader = retVal.AuthenticationHeader;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse> StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.DeleteTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest request) {
            return base.Channel.DeleteTRFreightCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostResponse> DeleteTRFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, int trNumber) {
            StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.DeleteTRFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.trNumber = trNumber;
            return ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).DeleteTRFreightCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateMvtFreightCost(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest request) {
            return base.Channel.UpdateMvtFreightCost(request);
        }
        
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages UpdateMvtFreightCost(ref StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostInput updateMvtFreightCostInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateMvtFreightCostInput = updateMvtFreightCostInput;
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse retVal = ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateMvtFreightCost(inValue);
            AuthenticationHeader = retVal.AuthenticationHeader;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse> StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateMvtFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest request) {
            return base.Channel.UpdateMvtFreightCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostResponse> UpdateMvtFreightCostAsync(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostInput updateMvtFreightCostInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightCostRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateMvtFreightCostInput = updateMvtFreightCostInput;
            return ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateMvtFreightCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateMvtFreightCharge(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest request) {
            return base.Channel.UpdateMvtFreightCharge(request);
        }
        
        public StratixRuanDataLayer.StratixTransportFreightService.ServiceMessages UpdateMvtFreightCharge(ref StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeInput updateMvtFreightChargeInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateMvtFreightChargeInput = updateMvtFreightChargeInput;
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse retVal = ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateMvtFreightCharge(inValue);
            AuthenticationHeader = retVal.AuthenticationHeader;
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse> StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService.UpdateMvtFreightChargeAsync(StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest request) {
            return base.Channel.UpdateMvtFreightChargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeResponse> UpdateMvtFreightChargeAsync(StratixRuanDataLayer.StratixTransportFreightService.AuthenticationToken AuthenticationHeader, StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeInput updateMvtFreightChargeInput) {
            StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest inValue = new StratixRuanDataLayer.StratixTransportFreightService.UpdateMvtFreightChargeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.updateMvtFreightChargeInput = updateMvtFreightChargeInput;
            return ((StratixRuanDataLayer.StratixTransportFreightService.TransportFreightService)(this)).UpdateMvtFreightChargeAsync(inValue);
        }
    }
}
