//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratixRuanDataLayer.StratixLogoutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stratix.invera.com/services", ConfigurationName="StratixLogoutService.LogoutService")]
    public interface LogoutService {
        
        // CODEGEN: Generating message contract since message LogoutResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/security/Logout", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://stratix.invera.com/security/Logout", Name="StratixFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratixRuanDataLayer.StratixLogoutService.LogoutResponse Logout(StratixRuanDataLayer.StratixLogoutService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stratix.invera.com/security/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixLogoutService.LogoutResponse> LogoutAsync(StratixRuanDataLayer.StratixLogoutService.LogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class AuthenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class DataElementMessageList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataElementField;
        
        private string[] messageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataElement {
            get {
                return this.dataElementField;
            }
            set {
                this.dataElementField = value;
                this.RaisePropertyChanged("dataElement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("messageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stratix.invera.com/schema/common/datatypes")]
    public partial class ServiceMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnStatusField;
        
        private string[] messageListField;
        
        private DataElementMessageList[] dataElementMessageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnStatus {
            get {
                return this.returnStatusField;
            }
            set {
                this.returnStatusField = value;
                this.RaisePropertyChanged("returnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] messageList {
            get {
                return this.messageListField;
            }
            set {
                this.messageListField = value;
                this.RaisePropertyChanged("messageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataElementMessageList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public DataElementMessageList[] dataElementMessageList {
            get {
                return this.dataElementMessageListField;
            }
            set {
                this.dataElementMessageListField = value;
                this.RaisePropertyChanged("dataElementMessageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stratix.invera.com/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratixRuanDataLayer.StratixLogoutService.AuthenticationToken authenticationToken;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(StratixRuanDataLayer.StratixLogoutService.AuthenticationToken authenticationToken) {
            this.authenticationToken = authenticationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://stratix.invera.com/services", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://stratix.invera.com/services")]
        public StratixRuanDataLayer.StratixLogoutService.ServiceMessages ServiceMessagesHeader;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(StratixRuanDataLayer.StratixLogoutService.ServiceMessages ServiceMessagesHeader) {
            this.ServiceMessagesHeader = ServiceMessagesHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogoutServiceChannel : StratixRuanDataLayer.StratixLogoutService.LogoutService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogoutServiceClient : System.ServiceModel.ClientBase<StratixRuanDataLayer.StratixLogoutService.LogoutService>, StratixRuanDataLayer.StratixLogoutService.LogoutService {
        
        public LogoutServiceClient() {
        }
        
        public LogoutServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogoutServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogoutServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogoutServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratixRuanDataLayer.StratixLogoutService.LogoutResponse StratixRuanDataLayer.StratixLogoutService.LogoutService.Logout(StratixRuanDataLayer.StratixLogoutService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public StratixRuanDataLayer.StratixLogoutService.ServiceMessages Logout(StratixRuanDataLayer.StratixLogoutService.AuthenticationToken authenticationToken) {
            StratixRuanDataLayer.StratixLogoutService.LogoutRequest inValue = new StratixRuanDataLayer.StratixLogoutService.LogoutRequest();
            inValue.authenticationToken = authenticationToken;
            StratixRuanDataLayer.StratixLogoutService.LogoutResponse retVal = ((StratixRuanDataLayer.StratixLogoutService.LogoutService)(this)).Logout(inValue);
            return retVal.ServiceMessagesHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StratixRuanDataLayer.StratixLogoutService.LogoutResponse> StratixRuanDataLayer.StratixLogoutService.LogoutService.LogoutAsync(StratixRuanDataLayer.StratixLogoutService.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<StratixRuanDataLayer.StratixLogoutService.LogoutResponse> LogoutAsync(StratixRuanDataLayer.StratixLogoutService.AuthenticationToken authenticationToken) {
            StratixRuanDataLayer.StratixLogoutService.LogoutRequest inValue = new StratixRuanDataLayer.StratixLogoutService.LogoutRequest();
            inValue.authenticationToken = authenticationToken;
            return ((StratixRuanDataLayer.StratixLogoutService.LogoutService)(this)).LogoutAsync(inValue);
        }
    }
}
